#!/usr/bin/env python3
"""Build the Newton collision layer for the reBot gripper from the vendor MJCF.

Newton turns the asset's `physics:approximation = convexDecomposition` into
its own CoACD run, which splits the three gripper meshes into ~6450 hulls and
overflows the solver's contact buffer. The vendor MJCF ships a reviewed
decomposition of the same arm (reBot DevArm): 12 hulls
for `gripper_end` and 8 per finger, <= 64 vertices each. This script writes
those 28 hulls, expressed in each USD body's frame, to a small USD layer that
`scripts/isaac_materials.apply_newton_gripper_hulls` references at runtime.

Usage:
    python scripts/build_newton_gripper_hulls.py --menagerie <dir with rebot_devarm.xml>

The MJCF body frames of these three bodies coincide with the USD asset's
body frames (checked when the layer was built: bounding boxes agree within
1.7 mm per side, the hull inflation). Requires the `mujoco` package.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib

import mujoco
import numpy as np

SOURCE_COMMIT = "199a0fa587ef15408432c8c135212d81304de1e3"
SOURCE_XML_SHA256 = "28d69120da31f6ca3bb138e6a0805e972bcc879416373e89229e98c4b2122731"
BODIES = ("gripper_end", "gripper_left", "gripper_right")
OUT = pathlib.Path(__file__).resolve().parents[1] / "assets/newton/rebot_gripper_hulls.usda"


def hulls(model: mujoco.MjModel, body: str):
    b = model.body(body).id
    for gi in range(model.ngeom):
        if model.geom_bodyid[gi] != b or model.geom_type[gi] != mujoco.mjtGeom.mjGEOM_MESH:
            continue
        if model.geom_contype[gi] == 0 and model.geom_conaffinity[gi] == 0:
            continue  # visual
        mid = model.geom_dataid[gi]
        v = model.mesh_vert[model.mesh_vertadr[mid]:model.mesh_vertadr[mid] + model.mesh_vertnum[mid]]
        f = model.mesh_face[model.mesh_faceadr[mid]:model.mesh_faceadr[mid] + model.mesh_facenum[mid]]
        rot = np.zeros(9)
        mujoco.mju_quat2Mat(rot, model.geom_quat[gi])
        yield model.mesh(mid).name, model.geom_pos[gi] + v @ rot.reshape(3, 3).T, f


def fmt(values, per_line=4):
    items = [f"({', '.join(f'{x:.7g}' for x in row)})" if np.ndim(row) else str(int(row)) for row in values]
    lines = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    return "[\n            " + ",\n            ".join(lines) + "\n        ]"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--menagerie", required=True, type=pathlib.Path,
                    help="directory holding the pinned Seeed vendor rebot_devarm.xml")
    ap.add_argument("--out", type=pathlib.Path, default=OUT)
    args = ap.parse_args()
    xml = args.menagerie / "rebot_devarm.xml"
    digest = hashlib.sha256(xml.read_bytes()).hexdigest()
    if digest != SOURCE_XML_SHA256:
        raise ValueError("Expected the reviewed vendor MJCF; source hash differs")
    model = mujoco.MjModel.from_xml_path(str(xml))
    body_blocks, total = [], 0
    for body in BODIES:
        prims = []
        for name, pts, faces in hulls(model, body):
            total += 1
            prims.append(
                f'        def Mesh "{name}"\n        {{\n'
                f"            int[] faceVertexCounts = {fmt([3] * len(faces), 24)}\n"
                f"            int[] faceVertexIndices = {fmt(faces.reshape(-1), 24)}\n"
                f"            point3f[] points = {fmt(pts)}\n"
                f'            uniform token subdivisionScheme = "none"\n'
                f"        }}\n")
        body_blocks.append(f'    def Xform "{body}"\n    {{\n' + "\n".join(prims) + "    }\n")
    header = (
        "#usda 1.0\n(\n"
        f'    doc = """reBot DevArm gripper collision hulls for Newton, from Seeed reBot-Isaacsim '
        f"rebot_devarm.xml @ {SOURCE_COMMIT} (sha256 {digest}). {total} convex hulls in each USD body's "
        f'frame. Generated by scripts/build_newton_gripper_hulls.py; do not edit by hand."""\n'
        '    defaultPrim = "Hulls"\n    metersPerUnit = 1\n    upAxis = "Z"\n)\n\n'
    )
    text = header + 'def Scope "Hulls"\n{\n' + "\n".join(body_blocks) + "}\n"
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {total} hulls to {args.out} (source sha256 {digest[:12]})")


if __name__ == "__main__":
    main()
